stages:
  - build
  - test
  - package

default:
  image: registry.gitlab.eox.at/maps/docker-base/mapchete:2023.1.1

build:
  stage: build
  tags:
    - dind-test
  artifacts:
    paths:
      - dist/
  before_script:
    - pip install --upgrade hatch
  script:
    - hatch build

test_wheel_base_image:
  stage: test
  tags:
    - dind-test
  timeout: 30m
  variables:
    MAPCHETE_IO_RETRY_DELAY: 2
    MAPCHETE_IO_RETRY_TRIES: 7
    GDAL_HTTP_MAX_RETRY: 5
    GDAL_HTTP_TIMEOUT: 30
    GDAL_HTTP_RETRY_DELAY: 5
  script:
    - pip install
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      --upgrade
      `ls dist/mapchete_eo*.whl -1 | head -1`[test]
    - pytest -v --cov=mapchete_eo tests/ --cov-report html --cov-report xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - htmlcov
      - coverage.xml
    when: on_success
    expire_in: 1 week
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"

test_tar_base_image:
  stage: test
  tags:
    - dind-test
  timeout: 30m
  variables:
    MAPCHETE_IO_RETRY_DELAY: 2
    MAPCHETE_IO_RETRY_TRIES: 7
    GDAL_HTTP_MAX_RETRY: 5
    GDAL_HTTP_TIMEOUT: 30
    GDAL_HTTP_RETRY_DELAY: 5
  script:
    - pip install
      --extra-index-url https://__token__:${EOX_PYPI_TOKEN}@gitlab.eox.at/api/v4/projects/255/packages/pypi/simple
      --upgrade
      `ls dist/mapchete_eo*.tar.gz -1 | head -1`[test]
    - pytest -v --cov=mapchete_eo tests/ --cov-report html --cov-report xml
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - htmlcov
      - coverage.xml
    when: on_success
    expire_in: 1 week
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
package:
  stage: package
  tags:
    - dind-test
  before_script:
    - pip install --upgrade hatch
  script:
    - hatch publish -r https://gitlab.eox.at/api/v4/projects/255/packages/pypi dist/mapchete_eo*
  only:
    - tags
