name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[docs]
          pip install sphinx sphinx-rtd-theme

      - name: Build HTML docs
        run: |
          sphinx-build -b html docs/source build

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: build/
