name: sync-dependencies

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  sync-dependencies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Sync and Upgrade
        run: |
          uv lock --upgrade

      - name: Sync Conda Recipe
        run: |
          uvx pyproject2conda yaml \
            -f pyproject.toml \
            --output conda/meta.yaml \
            --python-include infer
            
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update uv.lock and conda recipe"
          title: "chore(deps): sync uv and conda dependencies"
          body: |
            ### Automated Dependency Sync
            This PR ensures the lockfile and Conda recipe match `pyproject.toml`.
          branch: "automated-dependency-sync"
          base: ${{ github.event.pull_request.base.ref || 'main' }}
          delete-branch: true
          assignees: Scartography
          reviewers: ungarj
          labels: |
            dependencies
            automated-pr